"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Person = "Ekta" | "Ritesh";
type Category = "Groceries" | "Food" | "Wi-Fi" | "Water" | "Household" | "Other";
type Purchase = { id: string; label: string; category: Category; amount: number; paidBy: Person; date: string; trackForRestock: boolean; estimatedUseBy?: string; personal: boolean };
type Settlement = { id: string; payer: Person; receiver: Person; amount: number; date: string };
type LedgerData = { purchases: Purchase[]; settlements: Settlement[] };

const storageKey = "grocery-ledger-web-v1";
const categories: Category[] = ["Groceries", "Food", "Wi-Fi", "Water", "Household", "Other"];
const inr = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });
const today = () => new Date().toISOString().slice(0, 10);
const formatDate = (value: string) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`));
const normalize = (label: string) => label.toLowerCase().replace(/\((pack|pouch|box|packet)\)/g, "").replace(/\s+/g, " ").trim();

const demoData: LedgerData = { purchases: [
  { id: "demo-1", label: "Paneer", category: "Groceries", amount: 130, paidBy: "Ekta", date: "2026-06-18", trackForRestock: true, personal: false },
  { id: "demo-2", label: "Paneer", category: "Groceries", amount: 135, paidBy: "Ritesh", date: "2026-07-01", trackForRestock: true, personal: false },
  { id: "demo-3", label: "Milk", category: "Groceries", amount: 68, paidBy: "Ekta", date: "2026-07-04", trackForRestock: true, personal: false },
  { id: "demo-4", label: "Milk", category: "Groceries", amount: 70, paidBy: "Ekta", date: "2026-07-10", trackForRestock: true, estimatedUseBy: "2026-07-15", personal: false },
  { id: "demo-5", label: "Wi-Fi bill", category: "Wi-Fi", amount: 799, paidBy: "Ritesh", date: "2026-07-05", trackForRestock: false, personal: false },
], settlements: [] };

export default function Home() {
  const [data, setData] = useState<LedgerData>({ purchases: [], settlements: [] });
  const [ready, setReady] = useState(false); const [showAdd, setShowAdd] = useState(false); const [showSettle, setShowSettle] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { try { const saved = window.localStorage.getItem(storageKey); if (saved) setData(JSON.parse(saved)); } catch { setMessage("Saved browser data could not be read. Start with a new local ledger."); } setReady(true); }, []);
  useEffect(() => { if (ready) window.localStorage.setItem(storageKey, JSON.stringify(data)); }, [data, ready]);
  const balance = useMemo(() => { let ekta = 0; for (const item of data.purchases) { if (!item.personal) ekta += item.paidBy === "Ekta" ? item.amount / 2 : -item.amount / 2; } for (const item of data.settlements) ekta += item.payer === "Ekta" ? item.amount : -item.amount; return ekta; }, [data]);
  const suggestions = useMemo(() => {
    const groups = new Map<string, Purchase[]>();
    data.purchases.filter((item) => !item.personal && item.trackForRestock && (item.category === "Groceries" || item.category === "Household")).forEach((item) => groups.set(normalize(item.label), [...(groups.get(normalize(item.label)) ?? []), item]));
    return [...groups.entries()].flatMap(([id, items]) => { const ordered = [...items].sort((a, b) => a.date.localeCompare(b.date)); const dates = [...new Set(ordered.map((item) => item.date))]; if (dates.length < 2) return []; const last = dates.at(-1)!; const prior = dates.at(-2)!; const latest = ordered.at(-1)!; const interval = Math.max(1, Math.round((Date.parse(`${last}T12:00:00`) - Date.parse(`${prior}T12:00:00`)) / 86_400_000)); const predicted = latest.estimatedUseBy ?? new Date(Date.parse(`${last}T12:00:00`) + interval * 86_400_000).toISOString().slice(0, 10); return [{ id, label: latest.label, count: dates.length, interval, predicted, estimate: Boolean(latest.estimatedUseBy) }]; }).sort((a, b) => a.predicted.localeCompare(b.predicted));
  }, [data]);
  const addPurchase = (purchase: Omit<Purchase, "id">) => { setData((current) => ({ ...current, purchases: [{ ...purchase, id: crypto.randomUUID() }, ...current.purchases] })); setMessage("Saved on this browser only."); setShowAdd(false); };
  const addSettlement = (settlement: Omit<Settlement, "id">) => { setData((current) => ({ ...current, settlements: [{ ...settlement, id: crypto.randomUUID() }, ...current.settlements] })); setMessage("Settlement recorded on this browser only."); setShowSettle(false); };
  const balanceMessage = Math.abs(balance) < 0.005 ? "All settled up" : balance > 0 ? `Ritesh owes Ekta ${inr.format(balance)}` : `Ekta owes Ritesh ${inr.format(Math.abs(balance))}`;
  return <main><header className="topbar"><div className="wordmark"><span className="wordmark-mark">GL</span><span>Grocery Ledger</span></div><span className="local-pill">Browser-only data</span></header>
    <section className="hero"><div><p className="eyebrow">SHARED HOME LEDGER</p><h1>Split the bill.<br /><em>See what’s next.</em></h1><p className="lede">A small, private ledger for shared groceries, bills, and gentle restock cues. No receipt images or payment information are kept.</p></div><div className="hero-note"><span>Today’s balance</span><strong>{balanceMessage}</strong><small>Equal split between Ekta and Ritesh</small></div></section>
    <section className="actions"><button className="button primary" onClick={() => setShowAdd(true)}>＋ Add expense</button><button className="button secondary" onClick={() => setShowSettle(true)}>↔ Record settlement</button><button className="button text" onClick={() => { setData(demoData); setMessage("Demo data loaded. It is safe to clear at any time."); }}>Load demo data</button></section>{message && <p className="status" role="status">{message}</p>}
    <section className="grid"><article className="panel restock-panel"><div className="panel-title"><div><p className="eyebrow">RESTOCK</p><h2>Possible buys</h2></div><span className="panel-icon">⌁</span></div>{suggestions.length === 0 ? <div className="empty"><strong>No suggestion yet.</strong><span>Mark a grocery or household item for restock twice on different dates. The latest two purchases set the first interval.</span></div> : <ul className="suggestions">{suggestions.map((item) => <li key={item.id}><div><strong>{item.label}</strong><span>{item.estimate ? "Estimated use-by" : `Latest interval: ${item.interval} days`} · seen {item.count} times</span></div><time className={item.predicted <= today() ? "due" : ""}>{item.predicted <= today() ? "Review now" : `Around ${formatDate(item.predicted)}`}</time></li>)}</ul>}</article><article className="panel privacy-panel"><p className="eyebrow">PRIVACY PROMISE</p><h2>Only the reviewed ledger.</h2><ul><li>Receipt PDFs are not uploaded or saved here.</li><li>No address, payment mode, card or UPI details.</li><li>Use this web version for manual-entry testing.</li></ul></article></section>
    <section className="panel purchases-panel"><div className="panel-title"><div><p className="eyebrow">ACTIVITY</p><h2>Recent expenses</h2></div><span>{data.purchases.length} saved</span></div>{data.purchases.length === 0 ? <div className="empty"><strong>Start with one shared expense.</strong><span>Try the demo first, or add a grocery, food order, Wi-Fi, water, or household bill.</span></div> : <ul className="purchases">{[...data.purchases].sort((a, b) => b.date.localeCompare(a.date)).map((item) => <li key={item.id}><div className="purchase-symbol">{item.category === "Groceries" ? "◒" : item.category === "Food" ? "◉" : "◇"}</div><div className="purchase-main"><strong>{item.label}</strong><span>{item.category} · paid by {item.paidBy} · {formatDate(item.date)}{item.personal ? " · personal" : ""}</span></div><strong>{inr.format(item.amount)}</strong></li>)}</ul>} {data.purchases.length > 0 && <button className="clear" onClick={() => { setData({ purchases: [], settlements: [] }); setMessage("All browser-only data was cleared."); }}>Clear this browser’s data</button>}</section>
    <footer>Grocery Ledger web preview · local storage only · <span>not a replacement for the iPhone app’s PDF review</span></footer>{showAdd && <ExpenseDialog onClose={() => setShowAdd(false)} onSave={addPurchase} />}{showSettle && <SettlementDialog onClose={() => setShowSettle(false)} onSave={addSettlement} />}</main>;
}

function ExpenseDialog({ onClose, onSave }: { onClose: () => void; onSave: (purchase: Omit<Purchase, "id">) => void }) { const [label, setLabel] = useState(""); const [category, setCategory] = useState<Category>("Groceries"); const [amount, setAmount] = useState(""); const [paidBy, setPaidBy] = useState<Person>("Ekta"); const [date, setDate] = useState(today()); const [tracked, setTracked] = useState(false); const [personal, setPersonal] = useState(false); const [useBy, setUseBy] = useState(""); const submit = (event: FormEvent) => { event.preventDefault(); const value = Number(amount); if (!label.trim() || !Number.isFinite(value) || value <= 0) return; onSave({ label: label.trim(), category, amount: value, paidBy, date, trackForRestock: tracked && !personal, estimatedUseBy: tracked && useBy ? useBy : undefined, personal }); }; return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">NEW ENTRY</p><h2>Add expense</h2></div><button type="button" className="close" onClick={onClose} aria-label="Close">×</button></div><label>What was bought?<input autoFocus value={label} onChange={(e) => setLabel(e.target.value)} placeholder="e.g. Milk, Wi-Fi bill" /></label><div className="two-cols"><label>Category<select value={category} onChange={(e) => setCategory(e.target.value as Category)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Amount (₹)<input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="0.00" /></label><label>Paid by<select value={paidBy} onChange={(e) => setPaidBy(e.target.value as Person)}><option>Ekta</option><option>Ritesh</option></select></label><label>Date<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label></div>{(category === "Groceries" || category === "Household") && <><label className="checkbox"><input type="checkbox" checked={tracked} onChange={(e) => setTracked(e.target.checked)} /> Track this for restock</label>{tracked && <label>Optional estimated use-by<input type="date" value={useBy} onChange={(e) => setUseBy(e.target.value)} /></label>}</>}<label className="checkbox"><input type="checkbox" checked={personal} onChange={(e) => setPersonal(e.target.checked)} /> Personal item — exclude from split</label><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">Save expense</button></div></form></div>; }
function SettlementDialog({ onClose, onSave }: { onClose: () => void; onSave: (settlement: Omit<Settlement, "id">) => void }) { const [payer, setPayer] = useState<Person>("Ritesh"); const [amount, setAmount] = useState(""); const [date, setDate] = useState(today()); const submit = (event: FormEvent) => { event.preventDefault(); const value = Number(amount); if (!Number.isFinite(value) || value <= 0) return; onSave({ payer, receiver: payer === "Ekta" ? "Ritesh" : "Ekta", amount: value, date }); }; return <div className="modal-backdrop"><form className="modal compact" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">SETTLE UP</p><h2>Record payment</h2></div><button type="button" className="close" onClick={onClose} aria-label="Close">×</button></div><label>Who paid?<select value={payer} onChange={(e) => setPayer(e.target.value as Person)}><option>Ekta</option><option>Ritesh</option></select></label><label>Amount (₹)<input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="0.00" /></label><label>Date<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><p className="small-note">No payment reference, payment mode, or bank detail is collected.</p><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">Record settlement</button></div></form></div>; }
